<template>
  <div class="flex flex-col justify-start items-start">
    <h1
      v-motion-slide-visible-left
      class="
        text-3xl
        sm:text-4xl
        md:text-6xl
        font-bold
        bg-gradient-to-r
        from-primary
        to-secondary
        bg-clip-text
        text-transparent
        pb-4
      "
    >
      <slot></slot>
    </h1>
  </div>
</template>
